{"asctime": "2024-03-28 T14:51:50+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT\\src\\adapters\\transcription.py\", line 44, in recognize_from_file\n    conversation_transcriber = speechsdk.transcription.ConversationTranscriber(speech_config=speech_config, audio_config=audio_config)\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\transcription.py\", line 136, in __init__\n    _call_hr_fn(\n  File \"c:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\interop.py\", line 62, in _call_hr_fn\n    _raise_if_failed(hr)\n  File \"c:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\interop.py\", line 55, in _raise_if_failed\n    __try_get_error(_spx_handle(hr))\n  File \"c:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\interop.py\", line 50, in __try_get_error\n    raise RuntimeError(message)\nRuntimeError: Exception with error code: \n[CALL STACK BEGIN]\n\n    > pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - recognizer_create_speech_recognizer_from_config\n\n[CALL STACK END]\n\nException with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)", "location": "transcription.py - recognize_from_file"}
{"asctime": "2024-04-02 T14:12:39+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\app.py\", line 22, in Process_Audio_files\n    log_Garbage_Collector()\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 65, in log_Garbage_Collector\n    remove_old_logs_from_top(info_log_path)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 63, in remove_old_logs_from_top\n    info_logger.info(msg=\"Log Deleted\",extra={\"location\":\"logger.py - remove_old_logs_from_top\"})\n    ^^^^^^^^^^^\nNameError: name 'info_logger' is not defined", "location": "App.py - Process_Audio_files"}
{"asctime": "2024-04-02 T14:15:47+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\app.py\", line 22, in Process_Audio_files\n    log_Garbage_Collector()\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 65, in log_Garbage_Collector\n    remove_old_logs_from_top(info_log_path)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 63, in remove_old_logs_from_top\n    info_logger.info(msg=\"Log Deleted\",extra={\"location\":\"logger.py - remove_old_logs_from_top\"})\n    ^^^^^^^^^^^\nNameError: name 'info_logger' is not defined", "location": "App.py - Process_Audio_files"}
{"asctime": "2024-04-02 T14:17:35+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\app.py\", line 23, in Process_Audio_files\n    log_Garbage_Collector()\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 65, in log_Garbage_Collector\n    remove_old_logs_from_top(info_log_path)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 63, in remove_old_logs_from_top\n    info_logger.info(msg=\"Log Deleted\",extra={\"location\":\"logger.py - remove_old_logs_from_top\"})\n    ^^^^^^^^^^^\nNameError: name 'info_logger' is not defined", "location": "App.py - Process_Audio_files"}
{"asctime": "2024-04-02 T14:19:04+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\app.py\", line 23, in Process_Audio_files\n    log_Garbage_Collector()\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 66, in log_Garbage_Collector\n    remove_old_logs_from_top(info_log_path)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 64, in remove_old_logs_from_top\n    info_logger.info(msg=\"Log Deleted\",extra={\"location\":\"logger.py - remove_old_logs_from_top\"})\n    ^^^^^^^^^^^\nNameError: name 'info_logger' is not defined", "location": "App.py - Process_Audio_files"}
{"asctime": "2024-04-02 T14:20:04+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\app.py\", line 22, in Process_Audio_files\n    log_Garbage_Collector()\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 65, in log_Garbage_Collector\n    remove_old_logs_from_top(info_log_path)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 63, in remove_old_logs_from_top\n    info_logger.info(msg=\"Log Deleted\",extra={\"location\":\"logger.py - remove_old_logs_from_top\"})\n    ^^^^^^^^^^^\nNameError: name 'info_logger' is not defined", "location": "App.py - Process_Audio_files"}
{"asctime": "2024-04-02 T14:20:35+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\app.py\", line 23, in Process_Audio_files\n    log_Garbage_Collector()\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 65, in log_Garbage_Collector\n    remove_old_logs_from_top(info_log_path)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 63, in remove_old_logs_from_top\n    info_logger.info(msg=\"Log Deleted\",extra={\"location\":\"logger.py - remove_old_logs_from_top\"})\n    ^^^^^^^^^^^\nNameError: name 'info_logger' is not defined", "location": "App.py - Process_Audio_files"}
{"asctime": "2024-04-02 T14:21:01+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\app.py\", line 22, in Process_Audio_files\n    log_Garbage_Collector()\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 65, in log_Garbage_Collector\n    remove_old_logs_from_top(info_log_path)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\logs\\logger.py\", line 63, in remove_old_logs_from_top\n    info_logger.info(msg=\"Log Deleted\",extra={\"location\":\"logger.py - remove_old_logs_from_top\"})\n    ^^^^^^^^^^^\nNameError: name 'info_logger' is not defined", "location": "App.py - Process_Audio_files"}
{"asctime": "2024-04-02 T14:22:19+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\translator.py\", line 86, in get_translated_transcriptions\n    translated_dialogue = self.get_translated_transcriptions_pipeline(dialogue_info['dialogue'], dialogue_info['locale'], 'en')\n                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\translator.py\", line 59, in get_translated_transcriptions_pipeline\n    for item in self.transcriptions:\n                ^^^^^^^^^^^^^^^^^^^\nAttributeError: 'AzureTranslator' object has no attribute 'transcriptions'", "location": "main.py - get_translated_transcriptions"}
{"asctime": "2024-04-02 T14:22:19+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 103, in get_kpis\n    with open(transcription_jsonPath) as fp:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: expected str, bytes or os.PathLike object, not NoneType", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T15:37:12+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 118, in get_kpis\n    keyPhrase_obj = keyPhrase(transcripts= transcriptions)\n                    ^^^^^^^^^\nNameError: name 'keyPhrase' is not defined", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T16:46:34+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 112, in get_kpis\n    summarisation_result = obj.conversational_summarisation_helper(audio_name,transcription_jsonPath)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 153, in conversational_summarisation_helper\n    text_to_summarise_ls = self.get_conversational_text(json_path)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 142, in get_conversational_text\n    with open(transcription_jsonPath) as fp:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: expected str, bytes or os.PathLike object, not list", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T16:54:40+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 112, in get_kpis\n    summarisation_result = obj.conversational_summarisation_helper(audio_name,transcription_jsonPath)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 153, in conversational_summarisation_helper\n    text_to_summarise_ls = self.get_conversational_text(json_path)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 142, in get_conversational_text\n    with open(transcription_jsonPath) as fp:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: expected str, bytes or os.PathLike object, not list", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T16:56:57+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 112, in get_kpis\n    summarisation_result = obj.conversational_summarisation_helper(audio_name,transcription_jsonPath)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 153, in conversational_summarisation_helper\n    text_to_summarise_ls = self.get_conversational_text(json_path)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 142, in get_conversational_text\n    with open(transcription_jsonPath) as fp:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: expected str, bytes or os.PathLike object, not list", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T17:01:49+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 112, in get_kpis\n    summarisation_result = obj.conversational_summarisation_helper(audio_name,transcription_jsonPath)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 153, in conversational_summarisation_helper\n    text_to_summarise_ls = self.get_conversational_text(json_path)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 142, in get_conversational_text\n    with open(transcription_jsonPath,'r',encoding='utf-8') as fp:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: expected str, bytes or os.PathLike object, not list", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T17:04:35+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 112, in get_kpis\n    summarisation_result = obj.conversational_summarisation_helper(audio_name,transcription_jsonPath)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 155, in conversational_summarisation_helper\n    text_to_summarise_ls = self.get_conversational_text(json_path)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 143, in get_conversational_text\n    with open(transcription_jsonPath,'r',encoding='utf-8') as fp:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: expected str, bytes or os.PathLike object, not list", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T17:07:04+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 112, in get_kpis\n    summarisation_result = obj.conversational_summarisation_helper(audio_name,transcription_jsonPath)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 156, in conversational_summarisation_helper\n    text_to_summarise_ls = self.get_conversational_text(json_path)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 143, in get_conversational_text\n    with open(transcription_jsonPath,'r',encoding='utf-8') as fp:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: expected str, bytes or os.PathLike object, not list", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T17:19:37+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 112, in get_kpis\n    summarisation_result = obj.conversational_summarisation_helper(audio_name,transcription_jsonPath)\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\summarisation.py\", line 217, in conversational_summarisation_helper\n    result = self.get_conversational_summary(conversatioanl_summary_response)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: Summarization.get_conversational_summary() takes 1 positional argument but 2 were given", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T17:22:43+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 119, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T17:38:33+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 119, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T17:46:40+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 119, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T18:07:17+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 129, in get_kpis\n    keyPhrases = keyPhrase_obj.keyPhrase_pipeline()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\keyPhrase.py\", line 60, in keyPhrase_pipeline\n    result = self.keyPhrase_helper(item[\"dialogue\"])\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\src\\adapters\\keyPhrase.py\", line 54, in keyPhrase_helper\n    return output\n           ^^^^^^\nUnboundLocalError: cannot access local variable 'output' where it is not associated with a value", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-04-02 T19:00:14+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\Telecom EGYPT FASTAPI\\main.py\", line 187, in pipeline_after_transcription\n    merged_output[\"result\"][\"transcripts\"])\n    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\nKeyError: 'transcripts'", "location": "main.py - pipeline_after_transcription"}
