{"asctime": "2024-04-22 T18:43:54+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Celebal data\\Telecom Egypt\\fastapi\\Telecom%20Egypt%20Internal\\src\\adapters\\summarisation.py\", line 241, in conversational_summarisation_helper\n    error_msg =  f\"status code : {conversatioanl_summary_response.status_code}. Response : {conversatioanl_summary_response.text}\"\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'status_code'", "location": "summarisation.py - conversational_summarisation_helper"}
{"asctime": "2024-04-22 T18:45:53+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Celebal data\\Telecom Egypt\\fastapi\\Telecom%20Egypt%20Internal\\src\\adapters\\summarisation.py\", line 241, in conversational_summarisation_helper\n    error_msg =  f\"status code : {conversatioanl_summary_response.status_code}. Response : {conversatioanl_summary_response.text}\"\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'status_code'", "location": "summarisation.py - conversational_summarisation_helper"}
{"asctime": "2024-04-22 T18:48:24+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Celebal data\\Telecom Egypt\\fastapi\\Telecom%20Egypt%20Internal\\main.py\", line 569, in create_excel_for_powerbi\n    All_audio_result.to_excel(f\"Powerbi_reports/PowerBi_keywords_{calls_list[0]}-{calls_list[-1]}.xlsx\", index=False)\n  File \"C:\\Users\\MaharshiJasraj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\generic.py\", line 2252, in to_excel\n    formatter.write(\n  File \"C:\\Users\\MaharshiJasraj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\formats\\excel.py\", line 934, in write\n    writer = ExcelWriter(  # type: ignore[abstract]\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\MaharshiJasraj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\io\\excel\\_openpyxl.py\", line 56, in __init__\n    from openpyxl.workbook import Workbook\nModuleNotFoundError: No module named 'openpyxl'", "location": "main.py-create_excel_for_powerbi"}
{"asctime": "2024-04-22 T18:55:03+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Celebal data\\Telecom Egypt\\fastapi\\Telecom%20Egypt%20Internal\\src\\adapters\\summarisation.py\", line 241, in conversational_summarisation_helper\n    error_msg =  f\"status code : {conversatioanl_summary_response.status_code}. Response : {conversatioanl_summary_response.text}\"\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'status_code'", "location": "summarisation.py - conversational_summarisation_helper"}
{"asctime": "2024-04-22 T18:56:52+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Celebal data\\Telecom Egypt\\fastapi\\Telecom%20Egypt%20Internal\\src\\adapters\\summarisation.py\", line 241, in conversational_summarisation_helper\n    error_msg =  f\"status code : {conversatioanl_summary_response.status_code}. Response : {conversatioanl_summary_response.text}\"\n                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'status_code'", "location": "summarisation.py - conversational_summarisation_helper"}
